<?php

namespace AppBundle\Repository;

/**
 * FundDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundDataRepository extends \Doctrine\ORM\EntityRepository
{
}
