imports:
    - { resource: 'services/commands.yml' }
    - { resource: 'services/fetchers.yml' }
    - { resource: 'services/parsers.yml' }
    - { resource: 'services/score_calculators.yml' }
    - { resource: 'services/sorters.yml' }
