kurs-php:
  image: jakubsacha/symfony-docker:php5-dev
  links:
   - kurs-db
  ports:
   - "80:80"
  volumes:
   - ../:/var/www/html
kurs-db:
  image: mysql:5.5
  ports:
     - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
