services:
    app.command.fund.create:
        class: AppBundle\Command\FundCreateCommand
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            -  { name: console.command }

    app.command.fund.list:
        class: AppBundle\Command\FundListCommand
        arguments: ["@repository.fund", "@app.score_calculator.aggregate", "@app.fetcher.sorter"]
        tags:
            -  { name: console.command }

    app.command.async:
        class: AppBundle\Command\AbstractAsyncCommand
        arguments: ["%kernel.root_dir%"]
        abstract: true

    app.command.fund.fetch_data:
        parent: app.command.async
        class: AppBundle\Command\FundFetchDataCommand
        arguments: ["@app.fetcher.fund", "@repository.fund", "@doctrine.orm.default_entity_manager"]
        tags:
            -  { name: console.command }

    app.command.fund.fixtures:
        class: AppBundle\Command\FetchFundsListCommand
        arguments: ["@doctrine.orm.default_entity_manager", "%kernel.root_dir%", "%fund_filename%"]
        tags:
            -  { name: console.command }
